name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Inject clé Mailgun
        run: |
          sed -i "s/VOTRE_CLE_API_MAILGUN/${{ secrets.MAILGUN_API_KEY }}/g" send-email.php

      - name: Déploiement SFTP
        env:
          SFTP_HOST: ${{ secrets.SFTP_HOST }}
          SFTP_USER: ${{ secrets.SFTP_USER }}
          SFTP_PASSWORD: ${{ secrets.SFTP_PASSWORD }}
          SFTP_PORT: ${{ secrets.SFTP_PORT }}
          SFTP_PATH: ${{ secrets.SFTP_PATH }}
        run: |
          sudo apt-get install -y sshpass lftp
          lftp -u "$SFTP_USER","$SFTP_PASSWORD" -p "$SFTP_PORT" sftp://"$SFTP_HOST" <<EOF
          set sftp:connect-program "ssh -o StrictHostKeyChecking=no"
          set xfer:set-permissions false
          set cmd:fail-exit false
          mirror --reverse --delete --verbose \
            --exclude ^\.git/ \
            --exclude ^export_formation\.json$ \
            --exclude ^export_session\.json$ \
            --exclude ^organism\.json$ \
            . $SFTP_PATH
          bye
          EOF
