name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Inject clé Mailgun
        run: |
          sed -i "s/VOTRE_CLE_API_MAILGUN/${{ secrets.MAILGUN_API_KEY }}/g" send-email.php

      - name: Déploiement SFTP
        env:
          SFTP_HOST: ${{ secrets.SFTP_HOST }}
          SFTP_USER: ${{ secrets.SFTP_USER }}
          SFTP_PASSWORD: ${{ secrets.SFTP_PASSWORD }}
          SFTP_PORT: ${{ secrets.SFTP_PORT }}
          SFTP_PATH: ${{ secrets.SFTP_PATH }}
        run: |
          sudo apt-get install -y sshpass
          sshpass -p "$SFTP_PASSWORD" sftp -o StrictHostKeyChecking=no -P "$SFTP_PORT" "$SFTP_USER@$SFTP_HOST" <<EOF
          put -r . $SFTP_PATH
          EOF
